### ISSUE TITLE
Why is the module implementation different from the recommended one?

### ISSUE THREAD

**Issue by radub** [customgento/module-cookiebot-m2#17]
I've successfully installed and configured the module on a **Magento ver. 2.3.5-p2** project. After loading any page the cookiebot overlay was not rendered. Looking into the page source I found **a single script tag** similar to the following:
```
<script id="Cookiebot" 
        data-cfasync="false" 
        src="https://consent.cookiebot.com/uc.js" 
        data-cbid="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
        data-culture="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
        type="text/javascript" 
        async
>
</script> 
```
I have followed all installation steps in the module's documentation (https://github.com/customgento/module-cookiebot-m2#installation).  

In the module's documentation (https://github.com/customgento/module-cookiebot-m2#readme) the implementation consists in adding **two script tags** (module-cookiebot-m2 produces **a single script tag**):
 - one right before the HEAD tag is rendered 
 - one at the exact position where you would like the Cookie Declaration to appear.
I've disabled module-cookiebot-m2 and tested the recommended implementation and the cookiebot overlay was correctly displayed.

Please note that I have correctly listed the domain in the cookiebot management interface and configured it with the correct Cookiebot Domain Group ID. Also, Cookie-blocking mode is set to manual.

I'm a bit confused at this point because I'm thinking you had a good reason for implementing the module as you did so maybe I'm missing something here.

Can you please assist?

Thanks!

**Comment by sprankhub** [comment]
Sorry to hear you are having issues with the module.

**Our** documentation does not say anything about two scripts. Our module adds one script and that should be enough for the **cookie consent banner**. The [Cookiebot documentation](https://www.cookiebot.com/en/help/) talks about two scripts. However, the second script only renders the **cookie declaration**, which is usually added to one specific CMS page in Magento (like your privacy policy page). Since this highly depends on the shop, we do not add this second script.

However, if you see the general script tag correctly in your source code, the cookie consent banner should definitely show up. Did you maybe accept cookies once and that is why you do not see the banner again? Did you try it in a private window?

**Comment by radub** [comment]
@sprankhub It was a configuration issue on my side. The cookie consent banner is successfully displayed. 
Thank you for your assistance.

**Comment by sprankhub** [comment]
Glad to hear that it is solved :)
